"""add manual grade to problemsubmission

Revision ID: 7f934796475e
Revises: ca241219d94b
Create Date: 2023-10-30 13:44:06.406857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f934796475e'
down_revision = 'ca241219d94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problemsubmissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_grade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problemsubmissions', schema=None) as batch_op:
        batch_op.drop_column('manual_grade')

    # ### end Alembic commands ###
